import json
import os

json_path = r'c:\Users\Vaishnavi Trivedi\OneDrive\Desktop\manchester\MANCHESTER_ACCOMODATION\london All Data.json'
output_path = r'c:\Users\Vaishnavi Trivedi\OneDrive\Desktop\manchester\MANCHESTER_ACCOMODATION\src\data\londonAccommodations.ts'

def safe_int(val):
    if val is None or val == '':
        return 0
    try:
        if isinstance(val, str):
            # Clean non-numeric except dot
            val = ''.join(c for c in val if c.isdigit() or c == '.')
        return int(float(val))
    except (ValueError, TypeError):
        return 0

def safe_float(val):
    if val is None or val == '':
        return None
    try:
        return float(val)
    except (ValueError, TypeError):
        return None

def extract_accommodations():
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    houses = data.get('data', {}).get('houses', [])
    print(f"Found {len(houses)} houses in JSON.")
    
    accommodations = []
    
    for house in houses:
        # Mapping base fields
        acc = {
            "id": str(house.get('house_id', '')),
            "title": house.get('title', 'Untitled Property'),
            "address": house.get('address', 'London, UK'),
            "lat": safe_float(house.get('lat')) or 51.5074,
            "lng": safe_float(house.get('lng')) or -0.1278,
            "pricePerWeek": safe_int(house.get('rent_amount_value') or house.get('min_price')),
            "currency": house.get('price_currency', 'GBP'),
            "imageUrl": "https://images.unsplash.com/photo-1543393399-add3ef060b2d?auto=format&fit=crop&q=80&w=800", # default
            "university": house.get('school_name', 'University of London'),
            "universityDistance": house.get('school_distance', '0 km'),
            "roomTypes": [],
            "reviewScore": safe_float(house.get('review_avg_score')),
            "reviewCount": int(house.get('reviews_count', 0)) if house.get('reviews_count') else 0,
            "about": house.get('about', 'Premium London property.'),
            "supplier": house.get('supplier_name', 'London Living'),
        }
        
        # Clean up room_types
        raw_rooms = house.get('room_types')
        if isinstance(raw_rooms, list):
            for r in raw_rooms:
                if isinstance(r, str):
                    try:
                        # Sometimes it's a double-encoded string or just has leading/trailing garbage
                        # based on the previous view_file: "{\"{\\\"name\\\":\\\"En-suite\\\""
                        # It looks like it's a string containing another JSON string.
                        r_data = json.loads(r)
                        if isinstance(r_data, str):
                            r_data = json.loads(r_data)
                        if isinstance(r_data, dict) and 'name' in r_data:
                            acc['roomTypes'].append(r_data['name'])
                    except:
                        pass
        if not acc['roomTypes']:
            acc['roomTypes'] = ['Studio']
        
        # Try to get first image from media_image_paths
        media_paths = house.get('media_image_paths', '')
        if media_paths:
            if isinstance(media_paths, str):
                paths = media_paths.split(',')
                if paths:
                    img_path = paths[0].strip()
                    if img_path.startswith('//'):
                        acc['imageUrl'] = f"https:{img_path}"
                    elif img_path.startswith('/'):
                         # Use a placeholder if it's relative
                        acc['imageUrl'] = f"https://images.unsplash.com/photo-1543393399-add3ef060b2d?auto=format&fit=crop&q=80&w=800"
                    elif img_path.startswith('http'):
                        acc['imageUrl'] = img_path
        
        accommodations.append(acc)
        
    print(f"Extracted {len(accommodations)} accommodations.")
    
    # Generate the TS file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("import { Accommodation } from './manchesterData';\n\n")
        f.write("// Autogenerated from london All Data.json\n")
        f.write("export const EXTRACTED_LONDON_ACCOMMODATIONS_RAW: any[] = ")
        f.write(json.dumps(accommodations, indent=2))
        f.write(";\n")
        
    print(f"Written to {output_path}")

if __name__ == "__main__":
    extract_accommodations()
